# VE flow [Physics] -- coupled Exodus field variables (FE).
#
# Exercises the coupled-var path through the Physics action: phi_bar and the
# K_up components are passed as AuxVariable NAMES sourced from an Exodus mesh,
# rather than as the scalar constants used in the nc_sloped tests. This confirms
# that VEFlowPhysicsBase::assignCoupled correctly threads AuxVariable-name values
# through to the VEPorosity and VEPermeability materials it generates.
#
# Mirror of exodus/exodus_fields.i but using [Physics/VEFlow/FiniteElement] to
# generate the VEGeometry + VEPorosity + VEPermeability material chain. The solve
# is disabled (solve = false) so only the material-plumbing path is exercised.
#
# FV is not used here because VEFlowFV builds H inline in the kernels without
# creating a VEGeometry material (no ve_H MaterialProperty), so the material
# probes would fail. FE Physics creates VEGeometry and the regular MaterialProperty
# ve_H that MaterialRealAux requires.
#
# z_top / z_bottom are action-owned FE LAGRANGE variables, initialised with
# ParsedFunctions that match the generator's analytic fields exactly:
#   z_top   = -1000 + 0.02*x
#   z_bottom = -1100 - 0.03*x   (= z_top - H)
# so ve_H = z_top - z_bottom = 100 + 0.05*x -> 102.5 at (50,50).
#
# phi_bar and K_up_xx/yy/xy are read from the Exodus mesh as CONSTANT MONOMIAL
# AuxVariables, exercising the coupled-var path.
#
# At the element containing (50,50) the analytic fields give:
#   ve_H = 102.5, ve_phi_bar = 0.21,
#   ve_K_up = [[1.05e-12, 2.5e-14],[2.5e-14, 5e-13]].
# These match the exodus/exodus_fields.i gold exactly.

[Mesh]
  # Generated by test/tests/exodus/exodus_fields_generator.i (committed as .e).
  type = FileMesh
  file = '../exodus/exodus_fields_generator_out.e'
[]

[Problem]
  solve = false
  # FileMesh from an Exodus file triggers restart mode. z_top is a field name in
  # the file, so MOOSE would normally reject FunctionIC for it. This flag lets the
  # ICs override the restarted fields (we want the analytic z_top/z_bottom values,
  # not whatever the generator happened to leave in the file).
  allow_initial_conditions_with_restart = true
[]

[FluidProperties]
  [co2_fp]
    type = ConstantFluidProperties
    density = 700.0
    viscosity = 5.0e-5
  []
  [brine_fp]
    type = ConstantFluidProperties
    density = 1020.0
    viscosity = 8.0e-4
  []
[]

[UserObjects]
  [relperm_uo]
    type = VERelPermSharpUO
    S_wr = 0.0
    krn_max = 1.0
    krw_max = 1.0
  []
[]

# The Physics action creates pp_top, sat_n (FE LAGRANGE), z_top and z_bottom
# (FE LAGRANGE, define_geometry_variables = true default), and the full material
# chain. phi_bar / K_up_xx / K_up_yy / K_up_xy are forwarded from the
# user-declared CONSTANT MONOMIAL AuxVariables below.
[Physics/VEFlow/FiniteElement]
  [ve]
    phi_bar  = phi_bar    # coupled AuxVariable from Exodus, not a scalar constant
    K_up_xx  = K_up_xx   # coupled AuxVariable from Exodus
    K_up_yy  = K_up_yy   # coupled AuxVariable from Exodus
    K_up_xy  = K_up_xy   # coupled AuxVariable from Exodus
    fp_nw = co2_fp
    fp_w  = brine_fp
    relperm_uo = relperm_uo
  []
[]

# --- Petrophysical fields from the Exodus mesh (CONSTANT MONOMIAL) ---
[AuxVariables]
  [phi_bar]
    family = MONOMIAL
    order = CONSTANT
    initial_from_file_var = phi_bar
    initial_from_file_timestep = LATEST
  []
  [K_up_xx]
    family = MONOMIAL
    order = CONSTANT
    initial_from_file_var = K_up_xx
    initial_from_file_timestep = LATEST
  []
  [K_up_yy]
    family = MONOMIAL
    order = CONSTANT
    initial_from_file_var = K_up_yy
    initial_from_file_timestep = LATEST
  []
  [K_up_xy]
    family = MONOMIAL
    order = CONSTANT
    initial_from_file_var = K_up_xy
    initial_from_file_timestep = LATEST
  []

  # --- Material-property readouts ---
  [ve_H_out]
    family = MONOMIAL
    order = CONSTANT
  []
  [ve_phi_out]
    family = MONOMIAL
    order = CONSTANT
  []
  [ve_Kxx_out]
    family = MONOMIAL
    order = CONSTANT
  []
  [ve_Kxy_out]
    family = MONOMIAL
    order = CONSTANT
  []
  [ve_Kyy_out]
    family = MONOMIAL
    order = CONSTANT
  []
[]

[Functions]
  # Match the generator's analytic expressions so ve_H = z_top - z_bottom = H.
  [z_top_func]
    type = ParsedFunction
    expression = '-1000 + 0.02 * x'
  []
  [z_bottom_func]
    type = ParsedFunction
    expression = '-1100 - 0.03 * x' # z_top - H = (-1000 + 0.02*x) - (100 + 0.05*x)
  []
[]

[ICs]
  # z_top and z_bottom are declared by the Physics action (FE LAGRANGE); set their
  # spatially-varying values here to match the Exodus generator's analytic fields.
  [z_top_ic]
    type = FunctionIC
    variable = z_top
    function = z_top_func
  []
  [z_bottom_ic]
    type = FunctionIC
    variable = z_bottom
    function = z_bottom_func
  []
[]

[AuxKernels]
  [ve_H_aux]
    type = MaterialRealAux
    property = ve_H
    variable = ve_H_out
    execute_on = 'INITIAL'
  []
  [ve_phi_aux]
    type = MaterialRealAux
    property = ve_phi_bar
    variable = ve_phi_out
    execute_on = 'INITIAL'
  []
  [ve_Kxx_aux]
    type = MaterialRealTensorValueAux
    property = ve_K_up
    row = 0
    column = 0
    variable = ve_Kxx_out
    execute_on = 'INITIAL'
  []
  [ve_Kxy_aux]
    type = MaterialRealTensorValueAux
    property = ve_K_up
    row = 0
    column = 1
    variable = ve_Kxy_out
    execute_on = 'INITIAL'
  []
  [ve_Kyy_aux]
    type = MaterialRealTensorValueAux
    property = ve_K_up
    row = 1
    column = 1
    variable = ve_Kyy_out
    execute_on = 'INITIAL'
  []
[]

[Executioner]
  type = Transient
  end_time = 1
  dt = 1
[]

[Postprocessors]
  [H_probe]
    type = PointValue
    variable = ve_H_out
    point = '50 50 0'
    execute_on = 'INITIAL'
  []
  [phi_probe]
    type = PointValue
    variable = ve_phi_out
    point = '50 50 0'
    execute_on = 'INITIAL'
  []
  [Kxx_probe]
    type = PointValue
    variable = ve_Kxx_out
    point = '50 50 0'
    execute_on = 'INITIAL'
  []
  [Kxy_probe]
    type = PointValue
    variable = ve_Kxy_out
    point = '50 50 0'
    execute_on = 'INITIAL'
  []
  [Kyy_probe]
    type = PointValue
    variable = ve_Kyy_out
    point = '50 50 0'
    execute_on = 'INITIAL'
  []
[]

[Outputs]
  [csv]
    type = CSV
    execute_on = 'INITIAL'
  []
[]
