#pragma once

#include "PorousFlowCapillaryPressure.h"
#include "LinearInterpolation.h"

/**
 * VECapillaryPressureTableUO
 *
 * A PorousFlowCapillaryPressure UserObject backed by a piecewise-linear lookup
 * table of (Pc, Sw) pairs. Intended as the production-use companion to
 * VEPlumeReconstruction for real field models.
 *
 * Motivation
 * ----------
 * The parametric UOs (PorousFlowCapillaryPressureVG, BC) assume a single rock
 * type throughout the vertical column. Real formations have multiple stacked
 * facies, each with its own Pc curve. The fine-scale upscaling workflow already
 * integrates through all the vertical facies and produces a column-averaged
 * Sw(Pc) table as output. This class feeds that table directly into
 * VEPlumeReconstruction without forcing the data through a parametric fit that
 * may not represent the multi-facies column well.
 *
 * Different material blocks can reference different VECapillaryPressureTableUO
 * UOs to represent lateral variation in the facies sequence across the domain.
 *
 * Input
 * -----
 * pc_points  -- capillary pressure values [Pa], strictly increasing from 0
 * sw_points  -- true water saturation values [-], strictly decreasing,
 *               in one-to-one correspondence with pc_points
 *
 * Both vectors are supplied by the user (or generated by the upscaling
 * workflow) and pasted directly into the [UserObjects] block.
 *
 * Derivatives
 * -----------
 * First derivatives (dEffectiveSaturation, dCapillaryPressureCurve) are
 * piecewise-constant slopes of the linear segments -- exact for the
 * interpolant. Second derivatives are zero between breakpoints and undefined
 * at breakpoints; they are returned as 0.0, which is correct for the
 * piecewise-linear interpolant and acceptable for MOOSE's Newton solver in
 * practice.
 *
 * Set log_extension = false (the base-class logarithmic low-saturation
 * extension is not meaningful for a table with a finite lower Sw bound).
 */
class VECapillaryPressureTableUO : public PorousFlowCapillaryPressure
{
public:
  static InputParameters validParams();
  VECapillaryPressureTableUO(const InputParameters & parameters);

  virtual Real effectiveSaturation(Real pc, unsigned qp = 0) const override;
  virtual Real dEffectiveSaturation(Real pc, unsigned qp = 0) const override;
  virtual Real d2EffectiveSaturation(Real pc, unsigned qp = 0) const override;

  virtual Real capillaryPressureCurve(Real saturation, unsigned qp = 0) const override;
  virtual Real dCapillaryPressureCurve(Real saturation, unsigned qp = 0) const override;
  virtual Real d2CapillaryPressureCurve(Real saturation, unsigned qp = 0) const override;

private:
  /// Pc -> Sw interpolation (x = pc_points, y = sw_points).
  LinearInterpolation _pc_to_sw;

  /// Sw -> Pc interpolation (x = sw_points reversed to be increasing,
  /// y = pc_points reversed correspondingly).
  LinearInterpolation _sw_to_pc;
};
